facebook:
  verify: "rasa-bot"
  secret: "5bd5bde78e8f70b507bfcb70c1902263"
  page-access-token: "EAACQQtC9va0BAPSur1TVFwOkBJSWFZBYHp1HejzGmIOb6EhKxdA0kl4ZCtuIjlLmXT5IROJYHfPETnyQuKbTR8Ef1Dh0zkhNIuJqowZAo0V0LL5zqA9doZCzWaBqxZBCeaT5vSykELWf7QrtIOELxrXAavzRXu2VSeC1T5tUFIQZDZD"

rest:

